//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CachingMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GATOS
    {
        public string Id { get; set; }
        public string RAZA { get; set; }
        public string ORIGEN { get; set; }
        public string TIPO_PELO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string FECHA_LLEGADA { get; set; }
        public string FOTO { get; set; }
        public string INFO { get; set; }
    }
}
